#!/usr/bin/env python
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
import declarativewidgets.extensionapp

if __name__ == '__main__':
    declarativewidgets.extensionapp.main()